### Pandas Interview Questions


### 1. How to fill nan values in pandas with zero

### 1) Using fillna() method..

In [1]:
import pandas as pd
import numpy as np
  
Student_dict = {
    'Name': ['Jack', 'Rack', np.nan],
    'Marks':[100.5,np.nan, np.nan],
    'Subject': [np.nan, 'Math', 'Music']
}
  


In [2]:
print(Student_dict)

{'Name': ['Jack', 'Rack', nan], 'Marks': [100.5, nan, nan], 'Subject': [nan, 'Math', 'Music']}


In [3]:
### Convert Dictionary into DataFrame.

Student_df=pd.DataFrame(Student_dict)
print(Student_df)

   Name  Marks Subject
0  Jack  100.5     NaN
1  Rack    NaN    Math
2   NaN    NaN   Music


In [4]:
### Filling Nan Values with Zeroes.

Student_df['Marks']=Student_df['Marks'].fillna(0)
print(Student_df)

   Name  Marks Subject
0  Jack  100.5     NaN
1  Rack    0.0    Math
2   NaN    0.0   Music


### 2) Replace() method

In [5]:
Student_df1=Student_df.replace(np.nan,0)
print(Student_df)

   Name  Marks Subject
0  Jack  100.5     NaN
1  Rack    0.0    Math
2   NaN    0.0   Music


### 3) Fill NAN values with custom values.

In [6]:
Student_df

Name  Marks Subject
0  Jack  100.5     NaN
1  Rack    0.0    Math
2   NaN    0.0   Music

In [7]:
Student_df['Name'].fillna('Hitesh',inplace=True)

print(Student_df)

     Name  Marks Subject
0    Jack  100.5     NaN
1    Rack    0.0    Math
2  Hitesh    0.0   Music


In [8]:
Student_df['Subject'].isna()

0     True
1    False
2    False
Name: Subject, dtype: bool

### 1. How to create a NumPy 1-D array by using a Python list?

In [9]:
import numpy as np
arr_result=np.array([10,20,30,40,50,])
print(arr_result)

[10 20 30 40 50]


### 2. How To Create 2-Dimensional NumPy Array Using A List Of Lists?

In [12]:
num=[[1,2,3],[4,5,6],[6,7,8]]
result=np.array(num)
print("Two Dimentional array =",result)
print("Shape of two dimentional array =",result.shape)

Two Dimentional array = [[1 2 3]
 [4 5 6]
 [6 7 8]]
Shape of two dimentional array = (3, 3)


### 3) 3. How To Create NumPy Array Using Empty() Functions?

In [14]:
result=np.empty((3,3))
print("EMpty Array =",result)

EMpty Array = [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.16797119e-320]
 [1.09385465e-303 8.36324506e-299 9.12110623e-304]]


### 4) 4. How To Create NumPy Array Using Eye() Functions?

In [16]:
result_eye=np.eye(4)
print("Array =",result_eye)

Array = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 5.How To Create NumPy Array Using Ones() Function?

In [19]:
one_result=np.ones((5,5))
print(one_result)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### 6. How To Create NumPy Array Using Zeros() Function?

In [20]:
zero_result=np.zeros((4,4))
print(zero_result)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 7 How to use NumPy arrange() function to Create an array?

In [21]:
result_arr=np.arange(8)
print(result_arr)

[0 1 2 3 4 5 6 7]


In [25]:
result_arr=np.arange(8).reshape(2,4)
print(result_arr)

[[0 1 2 3]
 [4 5 6 7]]


### 8.How to create a NumPy array with step size?

In [33]:
result=np.arange(1,13,2).reshape(3,2)
print(result)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


### 9 How to create a matrix of numbers in NumPy?

In [35]:
result=np.random.randint(10,size=(3,3))
print(result)

[[7 6 0]
 [7 4 1]
 [0 7 5]]


### How to change the name of key in dictionary.

In [36]:
animaldict = {
  "name": "Dog",
  "age":5,
  "Weight": 4,
  "Country": "US",
  "City":"California"
   
}
print(animaldict)

{'name': 'Dog', 'age': 5, 'Weight': 4, 'Country': 'US', 'City': 'California'}


In [37]:
animaldict['AnimalName']=animaldict.pop('name')
print(animaldict)

{'age': 5, 'Weight': 4, 'Country': 'US', 'City': 'California', 'AnimalName': 'Dog'}


### How to delete a key from Dictionary

In [38]:
fruitsDict = {
  'Apple': 100,
  'Orange': 200,
  'Banana': 400,
  'pomegranate':600
}
print(fruitsDict)

{'Apple': 100, 'Orange': 200, 'Banana': 400, 'pomegranate': 600}


In [40]:
if 'Apple' in fruitsDict:
    del fruitsDict['Apple']

In [41]:
print(fruitsDict)

{'Orange': 200, 'Banana': 400, 'pomegranate': 600}


### How to get min and max keys corresponding to min and max value in Dictionary..

In [42]:
fruitsDict = {
  'Apple': 100,
  'Orange': 200,
  'Banana': 400,
  'pomegranate':600
}
print(fruitsDict)

{'Apple': 100, 'Orange': 200, 'Banana': 400, 'pomegranate': 600}


In [44]:
print("Min key in Dictionary ",min(fruitsDict,key=fruitsDict.get))
print("Max key in Dictionary ",max(fruitsDict,key=fruitsDict.get))

Min key in Dictionary  Apple
Max key in Dictionary  pomegranate


### How to concatenate multiple dictionary in one..

In [49]:
Fruit = {'Apple': 100, 'banana': 5}
 
Subject =  {'Math': 100, 'English': 98}
 
animal =  {'name': 'Rabbit', 'age': 1}


concat_dat={}

for dict in (Fruit,Subject,animal):
    concat_dat.update(dict)
print(concat_dat)

{'Apple': 100, 'banana': 5, 'Math': 100, 'English': 98, 'name': 'Rabbit', 'age': 1}


### How to sum all elements of Dictionary..

In [51]:
fruit = {'Apple': 100, 'banana': 5,'orange':45,'Guava':60}

print("Sum of all values =",sum(fruit.values()))

Sum of all values = 210


### How to sort a dictionary by key..

In [53]:
FruitDict = {'Apple': 10, 'Banana': 5,'Orange':4,'Guava':6}

### sorting dictionary.

for key in sorted(FruitDict):
    print(key,FruitDict[key])
    
    

Apple 10
Banana 5
Guava 6
Orange 4


In [54]:
for values in sorted(FruitDict):
    print(values,FruitDict[values])

Apple 10
Banana 5
Guava 6
Orange 4


### How do we find highest 2 values in a dictionary..