### 1) Write a NumPy program to get the numpy version and show numpy build configuration.

In [2]:
### FInding the version of numpy module.
import numpy as np
#print(np.__version__)

In [2]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


### Write a NumPy program to get help on the add function.

In [3]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### Write a NumPy program to test whether none of the elements of a given array is zero. all() function used.

In [4]:
## The numpy.all() function tests whether all array elements along the mentioned axis evaluate to True.

num=np.array([1,2,3,4,5])
print("Original Array ",num)
print()
print("Chekcing the element is zero or not.")
result=np.all(num)
print(result)
print()
num1=np.array([0,10,20,30,40])
print("Checking the element contain zero or not.")
result=np.all(num1)
print(result)


Original Array  [1 2 3 4 5]

Chekcing the element is zero or not.
True

Checking the element contain zero or not.
False


In [5]:
x=[1,2,3,4]
y=[sum(x[0:a+1]) for a in range(0,len(x))]
print(y)

[1, 3, 6, 10]


### Write a NumPy program to test whether any of the elements of a given array is non-zero. any() function used.

In [6]:
num=np.array([10,20,30,0,40])
print("Original array")
print(num)
print()
print("Chekcing any element contain zero or not")
result=np.any(num)
print(result)
print()
num=np.array([10,20,30,40,50])
result=np.any(num)
print("Checking any element conatain zero or not")
print(result)
num1=np.array([0,0,0,0,0])
print("original Array")
print(num1)
print()
print("Chekcing the array contain any element or not")
result=np.any(num1)
print(result)

Original array
[10 20 30  0 40]

Chekcing any element contain zero or not
True

Checking any element conatain zero or not
True
original Array
[0 0 0 0 0]

Chekcing the array contain any element or not
False


### The numpy.isinf() function tests element-wise whether it is +ve or -ve infinity or not return the result as a boolean array.  

In [7]:
a = np.array([1, 0, np.nan, np.inf,np.NINF])
print("Original array")
print(a)
print()
print("Chekcing number is positive or negative infinity")
result=np.isinf(a)
print(result)
print()

Original array
[  1.   0.  nan  inf -inf]

Chekcing number is positive or negative infinity
[False False False  True  True]



### Write a NumPy program to test element-wise for NaN of a given array. 

In [8]:
num=np.array([10,20,np.nan,np.inf,0,-20])
print("Oringinal array")
print(num)
result=np.isnan(num)
print(result)

Oringinal array
[ 10.  20.  nan  inf   0. -20.]
[False False  True False False False]


### Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [9]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print()
complex_number=np.iscomplex(a)
real_number=np.isreal(a)
num_type=np.isscalar(a)
print(complex_number)
print(real_number)
print(num_type)

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]

[ True False False False False  True]
[False  True  True  True  True False]
False


### Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [3]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print()
print("Original array")
print("x",x)
print("y",y)
print()
print("Chekcing element_wise operations.")
print()
greater_num=print("checking arary is greater or not =",np.greater(x,y))
greater_eq_num=print("chekcing array is great or equal =",np.greater_equal(x,y))
less_num=print("checking the arary is less or not =",np.less(x,y))
less_eq_num=print("chekcing the array is lese or equal =",np.less_equal(x,y))
equal_num=print("Checking both array are equal or not =",np.equal(x,y))
close_num=print("Chekcing tollerence of two array =",np.allclose(x,y))




Original array
x [  72   79   85   90  150 -135  120  -10   60  100]
y [  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]

Chekcing element_wise operations.

checking arary is greater or not = []
chekcing array is great or equal = [ True  True  True  True  True  True  True  True  True False]
checking the arary is less or not = [False False False False False False False False False  True]
chekcing the array is lese or equal = [ True  True  True  True  True  True  True  True  True  True]
Checking both array are equal or not = [ True  True  True  True  True  True  True  True  True False]
Chekcing tollerence of two array = True


### Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [11]:
x=np.array([1,7,13,105,10.50,10,20,"Hietsh","Sannu"])
print("Original array")
print(x)
print()
print("Chekcing the size iof array")
size=x.size
print(size)
print()
print("Checking the size of each elements")
item_s=x.itemsize
print(item_s)



Original array
['1' '7' '13' '105' '10.5' '10' '20' 'Hietsh' 'Sannu']

Chekcing the size iof array
9

Checking the size of each elements
128


### Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [12]:
zero_num=np.zeros(10)
print("creating the arary with zeros values.")
print(zero_num)
print()
one_num=np.ones(10)
print("Creating the arraya with ones values")
print(one_num)
print()
five_num=np.ones(10)*5
print("Creating the array with 5 values.")
print(five_num)

creating the arary with zeros values.
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Creating the arraya with ones values
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Creating the array with 5 values.
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### Write a NumPy program to create an array of the integers from 30 to 70.

In [13]:
## Using arange() we can create the array between any range.
num=np.arange(30,71)
print("creating the array ranging between 30 to 70")
print(num)

creating the array ranging between 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


### Write a NumPy program to create an array of all the even integers from 30 to 70.

In [44]:
even_num=np.arange(30,70,4)
print("Creating the array whcih conatin even number")
print(even_num)
print()
for i in np.nditer(even_num):
    if i%3==0:
        print(i,"Number divisible by :-> 3")
    else:
        print(i,"Number not Divisible by :-> 3")
    

Creating the array whcih conatin even number
[30 34 38 42 46 50 54 58 62 66]

30 Number divisible by :-> 3
34 Number not Divisible by :-> 3
38 Number not Divisible by :-> 3
42 Number divisible by :-> 3
46 Number not Divisible by :-> 3
50 Number not Divisible by :-> 3
54 Number divisible by :-> 3
58 Number not Divisible by :-> 3
62 Number not Divisible by :-> 3
66 Number divisible by :-> 3


### Write a NumPy program to create a 3x3 identity matrix.

In [15]:
### by using the identity() we can create the identity metrix

In [45]:
identity_num=np.identity(5)
print("Creating the identitty metrix array")
print(identity_num)

Creating the identitty metrix array
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
identity_num=np.identity(5)
print("Creating the identitty metrix array")
print(identity_num)

Creating the identitty metrix array
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Write a NumPy program to generate a random number between 0 and 1.

In [18]:
### we can used random().normal() function to generate random number between any given range.
rand_num=np.random.normal(0,1,1)
print("Generating random number between 0 and 1")
print(rand_num)

Generating random number between 0 and 1
[0.69354818]


### Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [107]:
rand_num=np.random.normal(0,1,15).reshape(5,3)
print("Creating the 15 random number from standard normal distribution.")
print()
print(rand_num)

Creating the 15 random number from standard normal distribution.

[[ 0.49252149 -0.10446441  0.64336497]
 [ 0.12013211 -1.14414097 -0.26469058]
 [ 1.00558253  1.02274129 -2.0311033 ]
 [-0.43410262 -2.287421   -0.57760185]
 [-0.55241144 -0.72498671 -0.52370729]]


### Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.

In [57]:
vect_num=np.arange(15,55).reshape(8,5)
print("Original vector")
print(vect_num)
print()
print("Printing the vctor except first and last")
result=vect_num[1:-1]
print(result)

Original vector
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]]

Printing the vctor except first and last
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


### Write a NumPy program to create a 3X4 array.

In [21]:
num=np.arange(10,22).reshape(3,4)
print(num)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [22]:
num1=np.arange(10,50).reshape(4,10)
print(num1)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


### if we want to itereate over this array element then we can used numpy iterator funtion called as nditer().

In [23]:
### we can used nditer() with for loop
print("Original array")
print(num)
print()
print("Iterate over array.")
for i in np.nditer(num):
    print(i)

Original array
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Iterate over array.
10
11
12
13
14
15
16
17
18
19
20
21


In [24]:
for i in np.nditer(num1):
    print(i)

10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


### Write a NumPy program to create a vector of length 10 with values ​​evenly distributed between 5 and 50.

In [48]:
### to create the vector which is eveny distributed we can used linspace() function.

num=np.linspace(5,50,10)
print("Creeating an array which is evenely distributed")
print(num)
print()
for i in np.nditer(num):
    if i%10==0:
        print(i,"Number divisible by 10")
    else:
        print(i,"Number is not divisible by 10")

Creeating an array which is evenely distributed
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]

5.0 Number is not divisible by 10
10.0 Number divisible by 10
15.0 Number is not divisible by 10
20.0 Number divisible by 10
25.0 Number is not divisible by 10
30.0 Number divisible by 10
35.0 Number is not divisible by 10
40.0 Number divisible by 10
45.0 Number is not divisible by 10
50.0 Number divisible by 10


### Write a NumPy program to create a vector with values ​​from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [26]:
num=np.arange(0,21)
print("Original number")
print(num)
print()
print("Chaging the sign of number")
num[(num>=9) &(num<=15)]*=-1
print(num)

Original number
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Chaging the sign of number
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


### Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [27]:
num=np.random.randint(0,10,5)
print("Original array")
print(num)


Original array
[0 0 0 2 4]


### Write a NumPy program to multiply the values ​​of two given vectors.

In [38]:
x=np.arange(2,12,2)
y=np.arange(10,20,2)
print()
print("X_vector")
print(x)
print()
print("y-vector")
print(y)
print()
print("Multiply both vector")
result=x*y
print(result)


X_vector
[ 2  4  6  8 10]

y-vector
[10 12 14 16 18]

Multiply both vector
[ 20  48  84 128 180]


### Write a NumPy program to find the number of rows and columns of a given matrix.

In [53]:
num1=np.arange(10,50).reshape(5,8)
print("original array")
print(num1)
print()
print("Finding the number of rows and columns in given vector")
result=num1.shape  ### shape is used to find out the number of rows and columns in vector.
print(result)


original array
[[10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49]]

Finding the number of rows and columns in given vector
(5, 8)


### Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.

In [54]:
identity_matrix=np.identity(3)
print("identity matrix")
print(identity_matrix)

identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [66]:
num=np.ones((10,10))
print("Original array of vector")
print(num)
print()
num[1:-1,1:-1]=0
print("After modifying vector array")
print(num)


Original array of vector
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

After modifying vector array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [67]:
num=np.diag([1,2,3,4,5])
print("Main diagonal element")
print(num)

Main diagonal element
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [71]:
arbi_values=np.random.random((3,3,3))
print("Vector of arbitory values")
print(arbi_values)

Vector of arbitory values
[[[0.3052395  0.15745117 0.88675913]
  [0.53198896 0.414551   0.70720146]
  [0.94965126 0.38837445 0.63983929]]

 [[0.9179719  0.25684866 0.64143695]
  [0.56191008 0.6426117  0.47627881]
  [0.82263578 0.5199613  0.61060799]]

 [[0.08549615 0.33180954 0.63057041]
  [0.068756   0.74069575 0.58211906]
  [0.53234466 0.67679186 0.12653479]]]


### Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [77]:
x=np.arange(15,35).reshape(5,4)
print("Original array vector")
print(x)
print()
print("Sum of all elements")
print(np.sum(x))      
print()
print("Sum of all rows")
print(np.sum(x,axis=1))
print()
print("Sum of all columns")
print(np.sum(x,axis=0))

Original array vector
[[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]
 [31 32 33 34]]

Sum of all elements
490

Sum of all rows
[ 66  82  98 114 130]

Sum of all columns
[115 120 125 130]


### Write a NumPy program to compute the inner product of two given vectors.

In [87]:
num1=np.array([3,4,5])
num2=np.array([6,4,8])
print("Array of num1")
print()
print("Array of num2")
print()
result=np.dot(num1,num2)
print("Dot product of two vectors")
print(result)
print()
print("Checking two array are equal or not")
check_equal=num1==num2
print(check_equal)


Array of num1

Array of num2

Dot product of two vectors
74

Checking two array are equal or not
[False  True False]


### Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.

In [84]:
num=[[1,2,3],[4,5,6]]
print(num)
print(type(num))
print()
print("Convert list into array")
result=np.array(num)
print(result)
print(type(result))
print()
print("Converting array into list again")
result1=result.tolist()
print(result1)
print(type(result1))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>

Convert list into array
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

Converting array into list again
[[1, 2, 3], [4, 5, 6]]
<class 'list'>


### Write a NumPy program to create one-dimensional array of single, two and three digit numbers.

In [103]:
### one dimentional array.
one_D=np.arange(2,10)
print("One dimentional array")
print(one_D)
print()
two_D=np.arange(11,99)
print("two dimentional array")
print(two_D)
print()
three_D=np.arange(100,200)
print("three dimentional array")
print(three_D)

One dimentional array
[2 3 4 5 6 7 8 9]

two dimentional array
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82
 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98]

three dimentional array
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


In [106]:
x=np.arange(10,30).reshape(4,5)
print(x)
print()
print("Sorting array by row in acscending order")
print(np.sort(x))
print()
print("Sorting array by coolumns in ascending order")
print(np.sort(x,axis=0))

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Sorting array by row in acscending order
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Sorting array by coolumns in ascending order
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
