### 1) Write a NumPy program to compute the multiplication of two given matrixes.

In [4]:
import numpy as np

x=np.arange(4).reshape(2,2)
y=np.arange(4,8).reshape(2,2)
print(x)
print()
print(y)
print()
print("Product of two matrixes")
result=np.dot(x,y)
print(result)

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]

Product of two matrixes
[[ 6  7]
 [26 31]]


### 2) Write a NumPy program to compute the cross product of two given vectors.

In [5]:
result=np.cross(x,y)
result

array([-4, -4])

### 3) Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.

In [7]:
print(x)
print()
print("Finding the Eigen values and Eigen vector of matrix")
print()
e_val,e_vect=np.linalg.eig(x)
print("Eigen values =",e_val)
print("Eigen vector =",e_vect)

[[0 1]
 [2 3]]

Finding the Eigen values and Eigen vector of matrix

Eigen values = [-0.56155281  3.56155281]
Eigen vector = [[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


### 4) Write a NumPy program to compute the determinant of an array.

In [8]:
print("Original array")
print(x)
print()
print("Finding the determinant of matrix")
print()
result=np.linalg.det(x)
print("Determinant of matrix")
print(result)

Original array
[[0 1]
 [2 3]]

Finding the determinant of matrix

Determinant of matrix
-2.0


### 5) Write a NumPy program to compute the inverse of a given matrix.

In [9]:
print("Original matrix")
print(x)
print()
print("Computing the inverse of give matrix")
print()
result=np.linalg.inv(x)
print("Inverse of matrix")
print(result)

Original matrix
[[0 1]
 [2 3]]

Computing the inverse of give matrix

Inverse of matrix
[[-1.5  0.5]
 [ 1.   0. ]]


### 6) Write a NumPy program to compute the sum of the diagonal element of a given array.

In [12]:
x=np.arange(9).reshape(3,3)
print("Original martix")
print(x)
print()
print("Sum of diagonal elements of an array")
print()
result=np.trace(x)
print("Sum of diagonal elements of matrix are")
print()
print(result)

Original martix
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Sum of diagonal elements of an array

Sum of diagonal elements of matrix are

12


## **** Numpy Random Exercise Problem :- ****

### 1) Write a NumPy program to generate five random numbers from the normal distribution.

In [16]:
x=np.random.normal(size=5)
print("Five random number for normal distribution")
print()
print(x)


Five random number for normal distribution

[ 0.5367282  -1.9379076   0.77378983  0.69466593  0.66952826]


### 2) Write a NumPy program to generate six random integers between 10 and 30.

In [17]:
x=np.random.randint(10,30,size=6)
print("Random six integer betwwen 10 to 30")
print(x)

Random six integer betwwen 10 to 30
[12 13 28 16 11 28]


### 3) Write a NumPy program to create a 3x3x3 array with random values.

In [19]:
x=np.random.random(27).reshape(3,3,3)
print("Random numpy matrix of dimention 3*3*3")
print(x)

Random numpy matrix of dimention 3*3*3
[[[0.40243225 0.86303764 0.77141597]
  [0.43960969 0.19815504 0.03426508]
  [0.06400363 0.08053978 0.99747944]]

 [[0.57626319 0.12874195 0.24083389]
  [0.68004318 0.62727253 0.17064436]
  [0.06953345 0.40045238 0.09066598]]

 [[0.17251596 0.83915246 0.98474784]
  [0.3635083  0.32125061 0.3475883 ]
  [0.47032094 0.20862345 0.74439438]]]


### 4) Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [33]:
x=np.random.random(25).reshape(5,5)
print("Matrix of dimention 5*5")
print()
print(x)
print()
print("Finding the maximum and minimum values from given matrix")
print()
max_val=np.max(x)
min_val=np.min(x)
print("Maximum values from given matrix =",max_val)
print()
print("Minimum values from given matrix =",min_val)


Matrix of dimention 5*5

[[0.97258783 0.74104141 0.03449815 0.16522602 0.69818349]
 [0.30227944 0.32044025 0.05456284 0.88135092 0.10185766]
 [0.5915786  0.1053926  0.82941275 0.43088207 0.67418807]
 [0.27813575 0.66879268 0.11886273 0.98371233 0.29330944]
 [0.88319282 0.69173849 0.60105742 0.65233489 0.33442844]]

Finding the maximum and minimum values from given matrix

Maximum values from given matrix = 0.9837123334727429

Minimum values from given matrix = 0.03449815345068741


In [26]:
a=np.arange(10)
print(a)
print()
m_val=np.max(a)
min_val=np.min(a)
print("Max values",m_val)
print()
print("Min values",min_val)

[0 1 2 3 4 5 6 7 8 9]

Max values 9

Min values 0


### 5) Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [47]:
x=np.arange(10)
print("Original array")
print(x)
print()
result=np.random.permutation(x)
print("After shuffeling array")
print(result)

Original array
[0 1 2 3 4 5 6 7 8 9]

After shuffeling array
[6 9 8 3 2 0 1 7 4 5]


### 6) Write a NumPy program to normalize a 3x3 random matrix.

In [49]:
x=np.arange(9).reshape(3,3)
print("Original array")
print(x)
print()
max_num,min_num=np.max(x),np.min(x)
print(max_num)
print()
print(min_num)
print()
print("Normalization of matrix")
print()
norm_result=(x-min_num)/(max_num-min_num)
print("Normalization values")
print()
print(result)

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

8

0

Normalization of matrix

Normalization values

[6 9 8 3 2 0 1 7 4 5]


### 7) Write a NumPy program to create a random vector of size 10 and sort it.

In [51]:
x=np.random.random(size=10)
print(x)
print("After sorting vector")
result=np.sort(x)
print(result)

[0.94024954 0.67674358 0.64270772 0.9936019  0.99219884 0.42923396
 0.92864961 0.30866965 0.66433794 0.85637813]
After sorting vector
[0.30866965 0.42923396 0.64270772 0.66433794 0.67674358 0.85637813
 0.92864961 0.94024954 0.99219884 0.9936019 ]


### 8) Write a NumPy program to check two random arrays are equal or not.

In [53]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print()
print("Checking two random variable are equal or not.")
print()
result=np.allclose(x,y)
print(result)

First array:
[0 1 0 0 0 0]
Second array:
[0 1 1 1 0 1]

Checking two random variable are equal or not.

False


### 9) Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.

In [59]:
x=np.random.random(15)
print(x)
print()
print("Replacing max value by -1")
print()
x[np.argmax(x)]=-1
print(x)


[0.41073728 0.32745304 0.49709672 0.70692719 0.74417659 0.46157994
 0.41115791 0.86431357 0.30578333 0.1497763  0.0596518  0.84878694
 0.40458654 0.36455315 0.21421607]

Replacing max value by -1

[ 0.41073728  0.32745304  0.49709672  0.70692719  0.74417659  0.46157994
  0.41115791 -1.          0.30578333  0.1497763   0.0596518   0.84878694
  0.40458654  0.36455315  0.21421607]
